### ISSUE TITLE
if doing ak run instead of ak build on 1st run, error

### ISSUE THREAD

**Issue by rvalyi** [akretion/voodoo-template#16]
I got that stack if I started doing ak run instead of ak build:

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/rvalyi/.voodoo/shared/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/home/rvalyi/.voodoo/shared/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 626, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/rvalyi/.voodoo/shared/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1370, in _call
    return f()
  File "/home/rvalyi/.voodoo/shared/eggs/anybox.recipe.odoo-1.9.1-py2.7.egg/anybox/recipe/odoo/base.py", line 857, in install
    self.install_requirements()
  File "/home/rvalyi/.voodoo/shared/eggs/anybox.recipe.odoo-1.9.1-py2.7.egg/anybox/recipe/odoo/base.py", line 301, in install_requirements
    eggs_recipe.install()
  File "/home/rvalyi/.voodoo/shared/eggs/zc.recipe.egg-2.0.1-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/home/rvalyi/.voodoo/shared/eggs/zc.recipe.egg-2.0.1-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/home/rvalyi/.voodoo/shared/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/home/rvalyi/.voodoo/shared/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 635, in install
    for_buildout_run=for_buildout_run):
  File "/home/rvalyi/.voodoo/shared/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 477, in _get_dist
    dist, avail = self._satisfied(requirement)
  File "/home/rvalyi/.voodoo/shared/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 272, in _satisfied
    best_available = self._obtain(req, source)
  File "/home/rvalyi/.voodoo/shared/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 402, in _obtain
    if index.obtain(requirement) is None:
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 444, in obtain
    self.find_packages(requirement)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 428, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name+'/')
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 762, in scan_url
    self.process_url(url, True)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 326, in process_url
    page = self.process_index(url, page)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 405, in process_index
    self.scan_url(new_url)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 762, in scan_url
    self.process_url(url, True)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 305, in process_url
    f = self.open_url(url, "Download error on %s: %%s -- Some packages may not be found!" % url)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 701, in open_url
    return open_with_auth(url, self.opener)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 895, in _socket_timeout
    return func(_args, *_kwargs)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 1008, in open_with_auth
    fp = opener(request)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer

I think ak run should default to ak build when project is obviously not built yet. Not sure why this happenned.

**Comment by EBII** [comment]
Apparently it is supposed to make it :
https://github.com/akretion/ak/blob/master/ak/main.py#L60
